### ISSUE TITLE
Issue with Glance deployment

### ISSUE THREAD

**Issue by vpasias** [iorchard/pbos-ansible#1]
Dear Sirs,

I have successfully deployed pbos-ansible on Rocky Linux 8.6 hosts (3 controllers & storage controllers and 6 compute & storage nodes), by following the instructions in: 'https://github.com/iorchard/pbos-ansible', for the yoga Openstack release. After the deployment is successfully completed (with no error messages), when I enter the command: 'openstack image list', it gives me the next output:

Failed to contact the endpoint at http://192.168.20.100:9292 for discovery. Fallback to using that endpoint as the base url.
Failed to contact the endpoint at http://192.168.20.100:9292 for discovery. Fallback to using that endpoint as the base url.
The image service for : exists but does not have any supported versions.

, where 192.168.20.100 is the Keepalive service interface VIP (parameter: 'keepalived_vip_svc' in the relative 'vars.yml' file that I have used).
The other Openstack services are successfully deployed without any issues.
As a result of the aforementioned issue, no virtual machines can be created at the deployed Openstack infrastructure.
Please indicate what may be the cause of this issue.
Thank you in advance.

Best Regards,

Vasilios Pasias

**Comment by jijisa** [comment]
Hi, 
haproxy should listen on the port of that ip address.
Make sure there is glance-public in /etc/haproxy/haproxy.cfg like this.
```
listen glance-public
    bind 192.168.20.50:9292
    timeout client          10m
    timeout server          10m
    option forwardfor except 127.0.0.0/8
    balance roundrobin
    option httpchk GET /
    server bkos-yoga-1 192.168.21.51:9292 check inter 2s rise 2 fall 3
    server bkos-yoga-2 192.168.21.52:9292 check inter 2s rise 2 fall 3
    server bkos-yoga-3 192.168.21.53:9292 check inter 2s rise 2 fall 3
```

**Comment by vpasias** [comment]
Dear jijisa,

Thank you for your response and support.
The /etc/haproxy/haproxy.cfg was correct, as per the example.
The problem was that when using lvm as additional storage backend in addition to ceph (in vars.yml file). When using only ceph as storage backend (not lvm as additional storage backend) then the problem was resolved and the glance image service is correctly deployed and functioning.

Best Regards,

Vasilios Pasias
